Persistent-topic
scramjetorg/reference-apps pull request #18
Opened 2023-03-15 13:53 UTC by piotrek6641

Sequence that persistently stores given amount of data in a specified time.

2023-03-15 21:58 UTC, patuwwy commented on js/persistency-sequence-generate-topic/index.ts
> +            console.log(`finished in: ${(Date.now() - startTime).toString()} ms`);
Detailed summary :)

```suggestion
            console.log(`Finished in: ${(Date.now() - startTime).toString()} ms. Bytes generated: ${a} x ${dataSize} + ${dataAmount} = ${a * dataSize + dataAmount}`);
```

2023-03-15 22:00 UTC, patuwwy commented on js/persistency-sequence-generate-topic/index.ts
> +            const startTime = Date.now();
```suggestion
            const startTime = Date.now();
            
            console.log(`Generating ${dataSize} bytes every ${intervalDelay}ms ...`);
```

2023-03-15 22:00 UTC, patuwwy commented on js/persistency-sequence-generate-topic/index.ts
> +            while (dataAmount > dataSize) {
```suggestion
            while (dataAmount >= dataSize) {
```

2023-03-15 22:07 UTC, patuwwy commented on js/persistency-sequence-generate-topic/index.ts
> +        });
The output will end when the generator goes out. At that time, Instance will also be terminated. If you want to trigger this event multiple times you need to pipe Readable with the `{ end: false }` option. 

```suggestion
        this.on("new-test-start", () => {
            Readable.from(gen()).pipe(out, { end: false });
        });
```

2023-03-15 22:08 UTC, patuwwy commented on js/persistency-sequence-generate-topic/package.json
> +  "name": "persistecy-sequence-generate-topic",
not sure if it shouldn't be named "@scramjet/persistecy-sequence-generate-topic"

2023-03-15 22:09 UTC, patuwwy requested changes
see comments Bro

2023-03-15 23:08 UTC, patuwwy commented on js/persistency-sequence-generate-topic/index.ts
> +        });
```suggestion
        this.on("new-test-start", () => {
            if (!busy) {
                Readable.from(gen()).pipe(out);
            } else {
                console.log("I'm busy, man...");
            }
        });
```

2023-03-20 08:12 UTC, piotrek6641 commented
> see comments Bro

Thank you for suggestions bro :)

2023-03-28 11:51 UTC, patuwwy approved these changes

2023-04-20 08:42 UTC, merged